### ISSUE TITLE
Add `.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by grossir** [freelawproject/eyecite#204]
We need a pre-commit config that matches the PR checks:
https://github.com/freelawproject/eyecite/blob/c89661f0d83b8039449f228bdfce884207b097f2/.github/workflows/lint.yml#L50-L63

Courtlistener's config
https://github.com/freelawproject/courtlistener/blob/main/.pre-commit-config.yaml

**Comment by rsb-23** [comment]
Will this help?
```
pip install yuhi
yuhi add pre-commit
```

**Comment by alexandresgf** [comment]
Why not use Ruff and consolidate all the lint, sort, and formatting in one tool? We could avoid using three different tools and gain speed as a bonus (thanks, RUST).

It would be like:

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2 # Use the latest release
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1 # Use the latest release
    hooks:
      - id: mypy
```
And the configuration should be something like:

```toml
[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
]
```
